#include "general_test.hpp"

int main()
{
	istringstream input(" _ // It is like a no name variable\n"
						" _no_name_too // It can't be referenced\n"
						" MOUNTAIN "
						" LUCKY2GO "
						" LUCCA_CITY ");
	CREATE_LEX_DATA(&input);

	NEXT;
	EXPECTING_TOKEN(NO_NAMED_VARIABLE);
	EXPECTING_LEXEMA("_");
	DESTROY_LEXEMA;

	NEXT;
	EXPECTING_TOKEN(NO_NAMED_VARIABLE);
	EXPECTING_LEXEMA("_");
	DESTROY_LEXEMA;

	NEXT;
	EXPECTING_TOKEN(VARIABLE);
	EXPECTING_LEXEMA("MOUNTAIN");
	DESTROY_LEXEMA;

	NEXT;
	EXPECTING_TOKEN(VARIABLE);
	EXPECTING_LEXEMA("LUCKY2GO");
	DESTROY_LEXEMA;

	NEXT;
	EXPECTING_TOKEN(VARIABLE);
	EXPECTING_LEXEMA("LUCCA_CITY");
	DESTROY_LEXEMA;

	NEXT;
	EXPECTING_TOKEN(0);

	return 0;
}
